/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.KeyEvent;
import javax.swing.JInternalFrame;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.table.*;
import koneksi.config;
import java.util.logging.*;
import static koneksi.config.conn;


public class D_buku extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabmodel;
    
    Connection conn = koneksi.config.Conn();
    /**
     * Creates new form D_buku
     */
    public D_buku() {
        initComponents();
        this.setLocationRelativeTo(null);
        update.setEnabled(false);
        hapus.setEnabled(false);
        judul();
        AutoKode();
        tampil();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbuku = new javax.swing.JTable();
        tcari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tkd_buku = new javax.swing.JTextField();
        tjudul = new javax.swing.JTextField();
        tpenulis = new javax.swing.JTextField();
        tpenerbit = new javax.swing.JTextField();
        jtahun = new javax.swing.JTextField();
        th_pokok = new javax.swing.JTextField();
        th_jual = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        update = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        stok = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Books_48px_1.png"))); // NOI18N
        jLabel1.setText("Data Buku");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(395, 395, 395))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        tbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode Buku", "Judul", "Jenis", "Penulis", "Penerbit", "Tahun", "Stok", "Harga Pokok", "Harga Jual"
            }
        ));
        tbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbuku);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, 645, 416));

        tcari.setBorder(null);
        tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcariActionPerformed(evt);
            }
        });
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcariKeyReleased(evt);
            }
        });
        getContentPane().add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 78, 260, 29));

        jLabel3.setText("Judul");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 153, 71, 29));

        jLabel4.setText("Kode Buku");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 118, 71, 29));

        jLabel5.setText("Penerbit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 295, 71, 29));

        jLabel6.setText("Penulis");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 255, 71, 29));

        jLabel7.setText("Tahun");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 335, 71, 29));

        jLabel8.setText("Harga Pokok");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 416, 71, 29));

        jLabel9.setText("Harga Jual");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 451, 71, 29));
        getContentPane().add(tkd_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 122, 124, -1));
        getContentPane().add(tjudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 157, 124, -1));
        getContentPane().add(tpenulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 259, 124, -1));
        getContentPane().add(tpenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 299, 124, -1));

        jtahun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtahunKeyTyped(evt);
            }
        });
        getContentPane().add(jtahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 339, 124, -1));
        getContentPane().add(th_pokok, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 420, 124, -1));
        getContentPane().add(th_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 455, 124, -1));

        jLabel11.setText("Back");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 68, 67, -1));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 520, 71, -1));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 486, 71, -1));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 520, 71, -1));

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 486, -1, -1));

        jLabel14.setText("Jenis");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 220, 71, 29));

        jenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novel", "Sejarah", "Edukasi", "Tutorial" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 224, 124, -1));

        jLabel10.setText("Stok");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 370, 71, 29));

        stok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stokKeyTyped(evt);
            }
        });
        getContentPane().add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 374, 124, -1));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 78, 40, -1));

        setSize(new java.awt.Dimension(933, 593));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void judul(){
        Object[] judul = {"Kode Buku","Judul","Jenis","Penulis","Penerbit","Tahun","Stok","HargaPokok","HargaJual"};
        tabmodel = new DefaultTableModel(null,judul){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbuku.setModel(tabmodel);
    }
    public void AutoKode(){
           try{
                rs = conn.createStatement().executeQuery("SELECT * FROM buku ORDER BY kd_buku DESC");
                if(rs.next()){
                    String kode = rs.getString("kd_buku").substring(3);
                    String AN = "" + (Integer.parseInt(kode) + 1);
                    String Nol = "";
                    
                    if(AN.length() == 1){
                        Nol = "000";
                    }
                    else if(AN.length() == 2){
                        Nol = "00";
                    }
                    else if(AN.length() == 3){
                        Nol = "0";
                    }
                    else if(AN.length() == 4){
                        Nol = "";
                    }
                    tkd_buku.setText("K" + Nol + AN);
             
                }
                else{
                    tkd_buku.setText("K0001");
                }
                tkd_buku.enable(false);
                rs.close();
                
           }
           catch (Exception e) {
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
           
            
        }
    
    public void tampil(){
        try {
            st = conn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM buku");
            while (rs.next()) {                
                Object[] data = {
                    rs.getString("kd_buku"),
                    rs.getString("judul"),
                    rs.getString("jenis"),
                    rs.getString("penulis"),
                    rs.getString("penerbit"),
                    rs.getString("tahun"),
                    rs.getString("stok"),
                    rs.getString("harga_pokok"),
                    rs.getString("harga_jual"),
                };
                tabmodel.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void reset(){
        tkd_buku.setText("");
        tjudul.setText("");
        tpenulis.setText("");
        tpenerbit.setText("");
        jtahun.setText("");
        stok.setText("");
        th_pokok.setText("");
        th_jual.setText("");
        
        update.setEnabled(false);
        hapus.setEnabled(false);
    }
    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed
        
    }//GEN-LAST:event_tcariActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        Form_admin fa = new Form_admin();
        fa.show();
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        conn = config.Conn();
        if (tkd_buku.getText().equals("") || tjudul.getText().equals("") || tpenulis.getText().equals("") || tpenerbit.getText().equals("") || jtahun.getText().equals("") || th_pokok.getText().equals("") || th_jual.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf Isi Data Dahulu");
        }
        else{
            try {
                st = conn.createStatement();
                st.executeUpdate("INSERT INTO buku SET " + "kd_buku='"+tkd_buku.getText()+"', judul='"+tjudul.getText()+"', jenis='"+jenis.getSelectedItem()+"', penulis='"+tpenulis.getText()+"', penerbit='"+tpenerbit.getText()+"', tahun='"+jtahun.getText()+"', stok='"+stok.getText()+"', harga_pokok='"+th_pokok.getText()+"', harga_jual='"+th_jual.getText()+"'");
                judul();
                tampil();
                JOptionPane.showMessageDialog(null, "Tambah Data Berhasil");
                AutoKode();
                tjudul.setText("");
                tpenulis.setText("");
                tpenerbit.setText("");
                jtahun.setText("");
                stok.setText("");
                th_pokok.setText("");
                th_jual.setText("");
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void tbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbukuMouseClicked
        tkd_buku.setText(tabmodel.getValueAt(tbuku.getSelectedRow(), 0)+ "");    
        tjudul.setText(tabmodel.getValueAt(tbuku.getSelectedRow(), 1)+ "");
        jenis.setSelectedItem(tabmodel.getValueAt(tbuku.getSelectedRow(), 2)+ "");
        tpenulis.setText(tabmodel.getValueAt(tbuku.getSelectedRow(), 3)+ "");
        tpenerbit.setText(tabmodel.getValueAt(tbuku.getSelectedRow(), 4)+ "");
        jtahun.setText(tabmodel.getValueAt(tbuku.getSelectedRow(), 5)+ "");
        stok.setText(tabmodel.getValueAt(tbuku.getSelectedRow(), 6)+ "");
        th_pokok.setText(tabmodel.getValueAt(tbuku.getSelectedRow(), 7)+ "");
        th_jual.setText(tabmodel.getValueAt(tbuku.getSelectedRow(), 8)+ "");        
        tambah.setEnabled(false);
        update.setEnabled(true);
        hapus.setEnabled(true);
    }//GEN-LAST:event_tbukuMouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        conn = config.Conn();
        if (tkd_buku.getText().equals("") || tjudul.getText().equals("") || tpenulis.getText().equals("") || tpenerbit.getText().equals("") || jtahun.getText().equals("") || th_pokok.getText().equals("") || th_jual.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tidak Ada Data untuk di Reset");
        }
        else{
            reset();
            AutoKode();
            tambah.setEnabled(true);
        }
    }//GEN-LAST:event_resetActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Menghapus?", "Informasi", JOptionPane.YES_NO_OPTION);
        if (a == JOptionPane.YES_OPTION) {
            try {
                st = conn.createStatement();
                st.executeUpdate("DELETE FROM buku WHERE "+"kd_buku='"+tabmodel.getValueAt(tbuku.getSelectedRow(), 0)+"'");

                    JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
                    tampil();
                    reset();
                    AutoKode();
                }
             catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            st = conn.createStatement();
            st.executeUpdate("UPDATE buku SET " + "judul='"+tjudul.getText()+"', jenis='"+jenis.getSelectedItem()+"', penulis='"+tpenulis.getText()+"', penerbit='"+tpenerbit.getText()+"', tahun='"+jtahun.getText()+"', stok='"+stok.getText()+"', harga_pokok='"+th_pokok.getText()+"', harga_jual='"+th_jual.getText()+"' WHERE kd_buku='"+tkd_buku.getText()+"'");
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Update");
            tampil();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    private void tcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyReleased
        try{
            st = conn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM buku WHERE kd_buku like '%" + tcari.getText() + "%' or judul like '%" + tcari.getText() + "%' or jenis like '%" + tcari.getText() + "%' or penulis like '%" + tcari.getText() + "%' " + "or penerbit like '%" + tcari.getText() + "%' or tahun like '%" + tcari.getText() + "%' or stok like '%" + tcari.getText() + "%' or harga_pokok like '%" + tcari.getText() + "%' or harga_jual like '%" + tcari.getText() +"%'");
            while(rs.next()){
                Object[] data = {
                    rs.getString("kd_buku"),
                    rs.getString("judul"),
                    rs.getString("jenis"),
                    rs.getString("penulis"),
                    rs.getString("penerbit"),
                    rs.getString("tahun"),
                    rs.getString("stok"),
                    rs.getString("harga_pokok"),
                    rs.getString("harga_jual"),
                };
                tabmodel.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_tcariKeyReleased

    private void jtahunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtahunKeyTyped
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtahunKeyTyped

    private void stokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stokKeyTyped
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_stokKeyTyped

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new D_buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jenis;
    private javax.swing.JTextField jtahun;
    private javax.swing.JButton reset;
    private javax.swing.JTextField stok;
    private javax.swing.JButton tambah;
    public javax.swing.JTable tbuku;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField th_jual;
    private javax.swing.JTextField th_pokok;
    public javax.swing.JTextField tjudul;
    public javax.swing.JTextField tkd_buku;
    private javax.swing.JTextField tpenerbit;
    private javax.swing.JTextField tpenulis;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
